# general args
#datasets: tuple[str, Any, Any]
num_of_epochs: 300
cutting: 1.
verbose: False
verbose_cutting: 50.0

# compile params
loss_E_name: MyLoss #MyMseTanh
loss_sigma_name: null  #if null, sigma loss = E loss
apply_lr_decay: True
lr: 0.0001
lr_sigma: 0.0001
lr_decay: 0.002

# callbacks params
checkpoint_cutting: 1.0
early_stop_params:
  min_delta: 1.0e-06
  mode: min
  monitor: val_loss_E
  patience: 20