# general args
#datasets: tuple[str, Any, Any]
num_of_epochs: 200
cutting: 1.
verbose: False
verbose_cutting: 50.0

# compile params
loss_E_name: MyMae
loss_sigma_name: MyMaeForSigma  #if null, sigma loss = E loss
apply_lr_decay: False
lr: 0.005
lr_sigma: 0.005
lr_decay: 0.05

# callbacks params
checkpoint_cutting: 1.0
early_stop_params:
  min_delta: 1.0e-06
  mode: min
  monitor: val_loss_E
  patience: 20