# dataset args. Do not set a "regime" here!

#my path
#path_to_h5: /home/albert/Baikal/NeutrinoSelection/DataBlock/data/baikal_multi_1223_flat_signal_doubles_H8_Q2_S2/step3_all_normed.h5

#must be absolute!
path_to_h5: /home/albert/Baikal/DataProc/h5_files/NE_08_06_24_baikal_multi_1223_filtered_splitted.h5
batch_size: 512
start: 0
set_up_Q_lim: True
up_Q_lim: 100.
apply_add_gauss: True
apply_mult_gauss: True
g_add_stds: [0.1, 2., 2., 2., 1.]
q_noise_fraction: 0.1
use_weights: False