# ResnetRnnConsturctor
# Input Hyperparameters

rnn_start_inputs: []
#    # 1
#  - {units: 128,
#     return_sequences: True,
#     dropout: 0.1,
#     recurrent_dropout: 0.}
#     # 2
#  - {units: 64,
#     return_sequences: True,
#     dropout: 0.1,
#     recurrent_dropout: 0.}

res_block_inputs: #[]
   # 1
   - {
      id: {filters: 512,
           kernel_size: 8,
           strides: 1},
      cd: {filters: 512,
           kernel_size: 8,
           strides: 2},
      skip: {filters: 512,
             kernel_size: 16,
             strides: 2},
      }
   # 2
   - {
      id: {filters: 128,
           kernel_size: 4,
           strides: 1},
      cd: {filters: 128,
           kernel_size: 4,
           strides: 2},
      skip: {filters: 128,
             kernel_size: 8,
             strides: 2},
      }
#  # 3
#   - {
#     id: { filters: 64,
#           kernel_size: 3,
#           strides: 1 },
#     cd: { filters: 64,
#           kernel_size: 3,
#           strides: 2 },
#     skip: { filters: 64,
#             kernel_size: 5,
#             strides: 2 },
#   }

rnn_end_inputs: []
#    # 1
#  - {units: 256,
#     return_sequences: False,
#     dropout: 0.1,
#     recurrent_dropout: 0.
#     }
  #   # 2
  # - {units: 64,
  #    return_sequences: False}

pooling: True

dense_blocks: 
  - { units: 256,
     # activation: , # it is LRelu by default
      dropout: 0.1}
  - { units: 128,
     # activation: , # it is LRelu by default
      dropout: 0.1}

