# Input Hyperparameters

dense_blocks:
  - { units: 128,
     # activation: , # it is LRelu by default
      dropout: 0.2}
  - { units: 64,
   # activation: , # it is LRelu by default
     dropout: 0.2}
  - { units: 1,
     activation: 'linear',
     dropout: 0.1}
