# Input Hyperparameters

dense_blocks:
  - { units: 64,
     # activation: , # it is LRelu by default
      dropout: 0.1}
  - { units: 32,
   # activation: , # it is LRelu by default
     dropout: 0.1 }
  - { units: 1,
   # activation: , # it is LRelu by default
     dropout: 0.1 }
