# ResnetRnnConsturctor
# Input Hyperparameters

dense_blocks: # write null here, if don't want sigma block
  - {units: 64,
     # activation: , # it is LRelu by default
     dropout: 0.1}
  - {units: 16,
     # activation: , # it is LRelu by default
     dropout: 0.1 }
  - { units: 1,
      activation: shifted_relu,
      dropout: 0. }
