# Input Hyperparameters

dense_blocks:
  - { units: 128,
   # activation: , # it is LRelu by default
     dropout: 0.3}
  - { units: 64,
   # activation: , # it is LRelu by default
     dropout: 0.3}
  - { units: 1,
     activation: 'shifted_relu', # it is LRelu by default
     dropout: 0.3}
